// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrmkWhiRh2nyCBVHq2mZpX3gwrXDjV8CM',
    appId: '1:290672417841:web:e26df533b4f75fe8254910',
    messagingSenderId: '290672417841',
    projectId: 'uni-club-nwu',
    authDomain: 'uni-club-nwu.firebaseapp.com',
    storageBucket: 'uni-club-nwu.appspot.com',
    measurementId: 'G-3T73C5XPXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBk4kbJcHgtGcsAztFqN096eUD_NWvwlA',
    appId: '1:290672417841:android:de32ec65b64aee98254910',
    messagingSenderId: '290672417841',
    projectId: 'uni-club-nwu',
    storageBucket: 'uni-club-nwu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnZn9EMaNdwrzx7DO4DuTtAiCg9d5xc78',
    appId: '1:290672417841:ios:7779a303b85349eb254910',
    messagingSenderId: '290672417841',
    projectId: 'uni-club-nwu',
    storageBucket: 'uni-club-nwu.appspot.com',
    iosBundleId: 'com.example.uniClub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnZn9EMaNdwrzx7DO4DuTtAiCg9d5xc78',
    appId: '1:290672417841:ios:1900f2a12e92fc16254910',
    messagingSenderId: '290672417841',
    projectId: 'uni-club-nwu',
    storageBucket: 'uni-club-nwu.appspot.com',
    iosBundleId: 'com.example.uniClub.RunnerTests',
  );
}
